Updated README.md with correct link to the contributors page
MicrosoftDocs/OfficeDocs-O365ITPro pull request #1007
Opened 2022-04-06 16:34 UTC by pm0d

2022-04-07 01:45 UTC, yogkumgit commented
@JohanFreelancer9

2022-04-07 08:56 UTC, JohanFreelancer9 commented on README.md
> +When you contribute your work will go directly into the content set after being merged. It will then show up on docs.microsoft.com and you will be listed as a contributor at: https://github.com/Micro
```suggestion
When you contribute your work will go directly into the content set after being merged. It will then show up on docs.microsoft.com and you will be listed as a contributor at: https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/graphs/contributors.
```

2022-04-07 09:01 UTC, JohanFreelancer9 requested changes
Copy review - @pm0d, kindly commit the minor additional suggested change. Many thanks.

2022-04-08 00:55 UTC, JohanFreelancer9 approved these changes

2022-05-25 14:44 UTC, merged