Added Viva Core Information
MicrosoftDocs/OfficeDocs-O365ITPro pull request #1013
Opened 2023-02-16 20:38 UTC by DanLongMSFT

Viva Core licensed users will not be active and not pending. Added !note tag with explanation. Feel free to wordsmith this. Reach out if any questions.

2023-02-17 05:29 UTC, JohanFreelancer9 commented on yammer/manage-yammer-users/manage-users-across-their-lifecycle.md
> +> If you have Viva Core licensed to your users, they will instead show up as 'active' instead of 'pending'.
```suggestion
> [!NOTE]
> If you have Viva Core licensed to your users, they will appear as **Active** instead of **Pending**.
```

2023-02-17 05:30 UTC, JohanFreelancer9 requested changes
Copy review - @DanLongMSFT, kindly commit the suggested changes. Many thanks.

2023-09-21 14:07 UTC, yogkumgit commented
@DanLongMSFT Gentle reminder

2023-09-22 02:34 UTC, JohanFreelancer9 approved these changes

2023-09-22 14:58 UTC, yogkumgit commented
@DanLongMSFT Please review and pass all the validation checks.

2023-09-22 19:11 UTC, DanLongMSFT commented
Due to the file name change (with rebrand from Yammer to Viva Engage), have instead posted changes with https://github.com/MicrosoftDocs/Viva/pull/706. Included changes that were proposed by @JohanFreelancer9. 

@yogkumgit - Should see this get pushed soon to the Viva Engage documentation.

2023-09-22 19:11 UTC, closed without merging