re-word "shared with"
MicrosoftDocs/OfficeDocs-O365ITPro pull request #1014
Opened 2023-02-27 20:13 UTC by AdamOutcalt

Users are confused about the wording of "shared with", which is really about how many users can get real-time sync.

2023-02-27 21:04 UTC, TarkanSevilmis approved these changes

2023-02-27 21:08 UTC, AdamOutcalt commented
#sign-off

2023-02-28 05:41 UTC, JohanFreelancer9 commented on Office365-Planner/planner-limits.md
> +> A context is the association between a plan and a host container like a Teams tab. The limit on contexts is a limit on how many associations a plan can have.
```suggestion
> - An active task is a task that is not completed.
> - Delta sync lets users passively receive updates in real-time while the app is open. Users beyond the delta-sync limits will not see updates in real-time.
> - Most Planner plans are owned by a group. Plans created by other apps, and shown in Planner, may be owned by a user.
> - A context is the association between a plan and a host container like a Teams tab. The limit on contexts is a limit on how many associations a plan can have.
```

2023-02-28 05:42 UTC, JohanFreelancer9 requested changes
Copy review - @AdamOutcalt, kindly commit the suggested changes. Many thanks.

2023-03-02 00:36 UTC, AdamOutcalt commented
@JohanFreelancer9 , I've committed the suggested changes. Maybe. I am new to GitHub.

#sign-off

2023-03-02 04:18 UTC, JohanFreelancer9 approved these changes

2023-03-02 20:59 UTC, AdamOutcalt commented
@JohanFreelancer9 , as a newbie in this repo, what are my next steps? Do I have to ask someone to merge the pull request?

2023-03-03 08:45 UTC, JohanFreelancer9 commented
> @JohanFreelancer9 , as a newbie in this repo, what are my next steps? Do I have to ask someone to merge the pull request?

@AdamOutcalt, there is nothing more required from you at this time. The PR needs to be approved and then merged by the document owner/manager. @yogkumgit, can you please assist? Thanks.

2023-03-06 15:36 UTC, tiburd commented
@alekyaj 
Hi,
Do you approve of the proposed change in this PR?
Thank you!

2023-03-07 04:08 UTC, alekyaj commented
> @alekyaj Hi, Do you approve of the proposed change in this PR? Thank you!

Hi @tiburd, 
Approved. Please go ahead with merging this PR. Thanks.

2023-03-07 15:23 UTC, merged