Planner: Add Task Recurrence to export-user-data
MicrosoftDocs/OfficeDocs-O365ITPro pull request #1016
Opened 2023-04-24 22:49 UTC by DaMoksha

This feature has been in the product for some time; adding docs.

2023-04-25 08:18 UTC, JohanFreelancer9 commented on Office365-Planner/export-user-data.md
> +|Plan.Tasks.Recurrence.Schedule.Pattern.Interval|The interval applied to the candence kind. Values greater than 1 mean that a period will be skipped. Examples: for a Daily pattern, an Interval of 2 m
```suggestion
|Plan.Tasks.Recurrence.Schedule.Pattern|The pattern for recurrence. The pattern, along with the **Schedule.Range**, are used to calculate the **Schedule.NextOccurrenceDate**.|
|Plan.Tasks.Recurrence.Schedule.Pattern.IsDailyCadence|`True` for daily cadence (in which case **DaysOrDates** is empty). `False` otherwise (that is, for weekly, monthly, or yearly cadence).|
|Plan.Tasks.Recurrence.Schedule.Pattern.Interval|The interval applied to the cadence kind. Values greater than 1 mean that a period will be skipped. Examples: for a Daily pattern, an Interval of 2 means tasks will recur every two days (or every other day). For a monthly pattern, an Interval of 3 means tasks will recur every three months (aka quarterly).|
```

2023-04-25 08:18 UTC, JohanFreelancer9 commented on Office365-Planner/export-user-data.md
> +|Plan.Tasks.Recurrence.Schedule.Pattern.FirstDayOfWeek|The first day of the week (typically Sunday); this is only used by Weekly patterns, and is `null` for non-weekly patterns.|
```suggestion
|Plan.Tasks.Recurrence.Schedule.Pattern.FirstDayOfWeek|The first day of the week (typically Sunday); this is only used by weekly patterns, and is `null` for non-weekly patterns.|
```

2023-04-25 08:19 UTC, JohanFreelancer9 requested changes
Copy review - @DaMoksha, kindly commit the suggested changes. Many thanks.

2023-04-26 06:07 UTC, JohanFreelancer9 approved these changes

2023-04-27 02:08 UTC, DaMoksha commented
@tiburd I was advised to tag you, to discover what I need to do to get this merged. Thank you!

2023-04-27 18:26 UTC, efrene reviewed
I have not worked on Project for several years now and I am not the correct person to review this.

2023-04-27 18:32 UTC, efrene commented
I will check to see who might be able to review this.

2023-04-27 19:36 UTC, DaMoksha commented
> @DaMoksha Hi David,
> 
> I'll merge the PR after the article author (@efrene) approves.
> 
> At your earliest convenience, please complete your account setup so that your GitHub and Microsoft accounts are connected:
> 
> * [Set up your accounts](https://review.docs.microsoft.com/en-us/office-authoring-guide/contribute-get-started-setup-github-ro?branch=main)
> 
> Thank you!

maybe @ArshishKWork ?

2023-04-27 21:05 UTC, efrene commented
Approving now.  Thanks!

2023-04-27 21:05 UTC, merged

2023-04-27 21:26 UTC, efrene commented
@DaMoksha. Sorry for the delay. I looked up who you were and noticed you were in the same group as some of the folks I was going to ask to review. :-) Thanks!